name: Cron Job

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call API Endpoint
        run: |
          curl -X GET "https://signal-bot-git.vercel.app/api/api?format=json"
