name: Cron Job

on:
  schedule:
    - cron: '*/15 * * * *'  # 每15分钟执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call API Endpoint
        run: |
          curl -X GET ${{ secrets.VERCEL_URL }}/api
        env:
          VERCEL_URL: ${{ secrets.VERCEL_URL }}
