name: Cron Job

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Call API Endpoint
        run: |
          curl -X GET "https://bot.uykb.eu.org/api?format=json" \
          -H "Accept: application/json" \
          -H "User-Agent: GitHub-Action-Bot" \
          --fail \
          --retry 3 \
          --retry-delay 5
