name: Trigger API

on:
  schedule:
    - cron: '*/5 * * * *'  # 每5分钟运行一次

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Call API Endpoint
        run: curl -X GET https://signal-bot-git.vercel.app/api
